services:
  mysql:
    image: mysql:8.0.38
    container_name: db_booking
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local