server:
  port: 8080

app:
  api-prefix: /api/public/v1

spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: authentication_service
            uri: http://localhost:8081
            predicates:
              - Path=${app.api-prefix}/authentication/**
            filters:
              - RewritePath=${app.api-prefix}/authentication/(?<segment>.*), ${app.api-prefix}/${segment}
          - id: accommodation_service
            uri: http://localhost:8083
            predicates:
              - Path=${app.api-prefix}/accommodation/**
            filters:
              - RewritePath=${app.api-prefix}/accommodation/(?<segment>.*), ${app.api-prefix}/${segment}
          - id: notification_service
            uri: http://localhost:8082
            predicates:
              - Path=${app.api-prefix}/notification/**
            filters:
              - RewritePath=${app.api-prefix}/notification/(?<segment>.*), notification_service${app.api-prefix}/${segment}

