package constant

const (
	PENDING     = "PENDING"
	CONFIRMED   = "CONFIRMED"
	APPROVED    = "APPROVED"
	CHECKED_IN  = "CHECKED_IN"
	CHECKED_OUT = "CHECKED_OUT"
	CANCELLED   = "CANCELLED"
	REJECTED    = "REJECTED"
	COMPLETED   = "COMPLETED"
)
