package constant

const (
	ErrAccommodationNotFound        = "accommodation not found"
	ErrAccommodationAlreadyExist    = "accommodation already exist"
	ErrUnitNotFound                 = "unit not found"
	ErrBookingNotFound              = "booking not found"
	ErrUserNotFound                 = "user not found"
	ErrBookingUnitNotFound          = "booking unit not found"
	ErrBookingPromotionNotFound     = "booking promotion not found"
	ErrCacheKeyNil                  = "cache key nil"
	ErrForbiddenApprovedBooking     = "forbidden approved booking"
	ErrForbiddenRejectBooking       = "forbidden reject booking"
	ErrForbiddenCancelBooking       = "forbidden cancel booking"
	ErrForbiddenConfirmBooking      = "forbidden confirm booking"
	ErrForbiddenCheckInBooking      = "forbidden check in booking"
	ErrCancelBookingFailed          = "cancel booking failed"
	ErrPromotionNotValid            = "promotion not valid"
	ErrInventoryLockFailed          = "inventory lock failed"
	ErrNotEnoughUnitsAvailable      = "not enough units available"
	ErrUnitQuantityExceedsAvailable = "unit quantity exceeds available"
	ErrInventoryNoLongerAvailable   = "inventory no longer available"
	ErrQuickBookingNotFound         = "quick booking not found"
	ErrUnitNotBelongToAccommodation = "unit not belong to accommodation"
	ErrAccommodationIDRequired      = "accommodation ID is required"
	ErrPermissionDenied             = "permission denied"
)
