spring:
  application:
    name: rating_service
  datasource:
    username: user_booking
    password: secret
    url: jdbc:postgresql://${DB_HOST:host.docker.internal}:${DB_PORT:5432}/db_rating_service
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST:host.docker.internal}
      port: ${REDIS_PORT:6379}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_HOST:host.docker.internal}:${KAFKA_PORT:9094}
    consumer:
      group-id: rating_group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8089
  servlet:
    context-path: /rating_service

app:
  services:
    booking_service:
      url: ${BOOKING_SERVICE_HOST:host.docker.internal}:${NOTIFICATION_SERVICE_HOST:8084}/booking_service/
    profile_service:
      url: ${PROFILE_SERVICE_HOST:host.docker.internal}:${PROFILE_SERVICE_HOST:8086}/profile_service/
    accommodation_service:
      url: ${ACCOMMODATION_SERVICE_HOST:host.docker.internal}:${PROFILE_SERVICE_HOST:8083}/accommodation_service/
  security:
    jwt:
      secret: MnAYFOKwxBOznHpxA3Wx4cJjeC3vYNtwzI6HRYT9SD++1BM9Pk32pTGETroljFsS
      expiration: 86400000
      header: Authorization
      prefix: Bearer
    filter:
      publicUrls:
        - first: /api/public/v1/ratings/**
          second: GET
        - first: /api/public/v1/rating_summaries/**
          second: GET
      protectedUrls:
