spring:
  application:
    name: file_service
  datasource:
    username: user_booking
    password: secret
    url: jdbc:postgresql://localhost:5433/db_file_service
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8088