spring:
  application:
    name: authentication_service

  datasource:
    username: root
    password: root
#    url: jdbc:mysql://localhost:3309/authentication_service?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    url: jdbc:mysql://localhost:3309/authentication_service
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8081
