spring:
  application:
    name: accommodation_service

  datasource:
    username: user_booking
    password: secret
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/db_accommodation_service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379