spring:
  application:
    name: accommodation_service

  datasource:
    username: user_booking
    password: secret
    url: jdbc:postgresql://localhost:5433/db_accommodation_service
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  graphql:
    graphiql:
      enabled: true
    path: /graphql

app:
#  service:
  #    cors:
  #      baseUrl: http://localhost:3000
  #      allowedMethods:
  #        - GET
  #        - POST
  #        - PUT
  #        - DELETE
  #        - PATCH
  services:
    file_service:
      url: localhost:8088/file_service/
    rating_service:
      url: localhost:8089/rating_service
  kafka:
    default-server: localhost:9094
  security:
    jwt:
      secret: MnAYFOKwxBOznHpxA3Wx4cJjeC3vYNtwzI6HRYT9SD++1BM9Pk32pTGETroljFsS
      expiration: 86400000
      header: Authorization
      prefix: Bearer
    filter:
      publicUrls:
        - first: /api/public/v1/amenity_groups/**
          second: GET
        - first: /api/public/v1/languages/**
          second: GET
        - first: /api/public/v1/unit_names/**
          second: GET
        - first: /api/public/v1/bed_types/**
          second: GET
        - first: /api/public/v1/accommodation_types/**
          second: GET
        - first: /api/public/v1/price_types
          second: GET
        - first: /api/public/v1/accommodations/**
          second: GET
        - first: /api/internal/v1/accommodations/**
          second: GET
        - first: /api/internal/v1/units/**
          second: GET
        - first: /api/public/v1/currencies/**
          second: GET
      protectedUrls:
        - urlPattern: /api/public/v1/amenity_groups
          roles:
            - ADMIN
        - urlPattern: /api/public/v1/amenities
          roles:
            - ADMIN
        - urlPattern: /api/public/v1/languages
          roles:
            - ADMIN
        - urlPattern: /api/public/v1/unit_names
          roles:
            - ADMIN
        - urlPattern: /api/public/v1/bed_types
          roles:
            - ADMIN
        - urlPattern: /api/public/v1/accommodation_types
          roles:
            - ADMIN
        - urlPattern: /api/public/v1/accommodations
          roles:
            - ADMIN
            - HOST
        - urlPattern: /api/public/v1/currencies
          roles:
            - ADMIN

server:
  port: 8083
  servlet:
    context-path: /accommodation_service