spring:
  application:
    name: search_service
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 5s
    socket-timeout: 5s

  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: search_group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 10

server:
  port: 8085
  servlet:
    context-path: /search_service

app:
  services:
    accommodation_service:
      url: localhost:8083/accommodation_service
  elasticsearch:
    url: localhost:9200
    password: GdL=WfNXaAui4QTJaoIN
    username: elastic
  security:
    jwt:
      secret: MnAYFOKwxBOznHpxA3Wx4cJjeC3vYNtwzI6HRYT9SD++1BM9Pk32pTGETroljFsS
      expiration: 86400000
      header: Authorization
      prefix: Bearer
    filter:
      publicUrls:
        - first: /api/public/v1/search/**
          second: GET
        - first: /api/public/v1/accommodations/search/**
          second: POST
      protectedUrls:
        - urlPattern: /api/public/v1/**
          roles:
            - ADMIN