spring:
  application:
    name: search_service
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 5s
    socket-timeout: 5s

  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8085

app:
  elasticsearch:
    url: localhost:9200
    password: GdL=WfNXaAui4QTJaoIN
    username: elastic
  security:
    jwt:
      secret: MnAYFOKwxBOznHpxA3Wx4cJjeC3vYNtwzI6HRYT9SD++1BM9Pk32pTGETroljFsS
      expiration: 86400000
      header: Authorization
      prefix: Bearer
    filter:
      publicUrls:
        - first: /api/public/v1/search/**
          second: GET
      protectedUrls:
        - urlPattern: /api/public/v1/**
          roles:
            - ADMIN