// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: ui/proto/memo.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Memo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatorId     int64                  `protobuf:"varint,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Visibility    string                 `protobuf:"bytes,4,opt,name=visibility,proto3" json:"visibility,omitempty"`
	RowStatus     string                 `protobuf:"bytes,5,opt,name=row_status,json=rowStatus,proto3" json:"row_status,omitempty"`
	Pinned        bool                   `protobuf:"varint,6,opt,name=pinned,proto3" json:"pinned,omitempty"`
	ParentId      int64                  `protobuf:"varint,7,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Memo) Reset() {
	*x = Memo{}
	mi := &file_ui_proto_memo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Memo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Memo) ProtoMessage() {}

func (x *Memo) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_memo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Memo.ProtoReflect.Descriptor instead.
func (*Memo) Descriptor() ([]byte, []int) {
	return file_ui_proto_memo_proto_rawDescGZIP(), []int{0}
}

func (x *Memo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Memo) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *Memo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Memo) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *Memo) GetRowStatus() string {
	if x != nil {
		return x.RowStatus
	}
	return ""
}

func (x *Memo) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

func (x *Memo) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Memo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Memo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreateMemoDto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Visibility    string                 `protobuf:"bytes,3,opt,name=visibility,proto3" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMemoDto) Reset() {
	*x = CreateMemoDto{}
	mi := &file_ui_proto_memo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMemoDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemoDto) ProtoMessage() {}

func (x *CreateMemoDto) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_memo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemoDto.ProtoReflect.Descriptor instead.
func (*CreateMemoDto) Descriptor() ([]byte, []int) {
	return file_ui_proto_memo_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMemoDto) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateMemoDto) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateMemoDto) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

type GetMemoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemoRequest) Reset() {
	*x = GetMemoRequest{}
	mi := &file_ui_proto_memo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemoRequest) ProtoMessage() {}

func (x *GetMemoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_memo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemoRequest.ProtoReflect.Descriptor instead.
func (*GetMemoRequest) Descriptor() ([]byte, []int) {
	return file_ui_proto_memo_proto_rawDescGZIP(), []int{2}
}

func (x *GetMemoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_ui_proto_memo_proto protoreflect.FileDescriptor

const file_ui_proto_memo_proto_rawDesc = "" +
	"\n" +
	"\x13ui/proto/memo.proto\x12\x04memo\"\x81\x02\n" +
	"\x04Memo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x02 \x01(\x03R\tcreatorId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1e\n" +
	"\n" +
	"visibility\x18\x04 \x01(\tR\n" +
	"visibility\x12\x1d\n" +
	"\n" +
	"row_status\x18\x05 \x01(\tR\trowStatus\x12\x16\n" +
	"\x06pinned\x18\x06 \x01(\bR\x06pinned\x12\x1b\n" +
	"\tparent_id\x18\a \x01(\x03R\bparentId\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\"b\n" +
	"\rCreateMemoDto\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1e\n" +
	"\n" +
	"visibility\x18\x03 \x01(\tR\n" +
	"visibility\" \n" +
	"\x0eGetMemoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2m\n" +
	"\vMemoService\x12-\n" +
	"\n" +
	"CreateMemo\x12\x13.memo.CreateMemoDto\x1a\n" +
	".memo.Memo\x12/\n" +
	"\vGetMemoById\x12\x14.memo.GetMemoRequest\x1a\n" +
	".memo.MemoB\x15Z\x13memo_service/pkg/pbb\x06proto3"

var (
	file_ui_proto_memo_proto_rawDescOnce sync.Once
	file_ui_proto_memo_proto_rawDescData []byte
)

func file_ui_proto_memo_proto_rawDescGZIP() []byte {
	file_ui_proto_memo_proto_rawDescOnce.Do(func() {
		file_ui_proto_memo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ui_proto_memo_proto_rawDesc), len(file_ui_proto_memo_proto_rawDesc)))
	})
	return file_ui_proto_memo_proto_rawDescData
}

var file_ui_proto_memo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ui_proto_memo_proto_goTypes = []any{
	(*Memo)(nil),           // 0: memo.Memo
	(*CreateMemoDto)(nil),  // 1: memo.CreateMemoDto
	(*GetMemoRequest)(nil), // 2: memo.GetMemoRequest
}
var file_ui_proto_memo_proto_depIdxs = []int32{
	1, // 0: memo.MemoService.CreateMemo:input_type -> memo.CreateMemoDto
	2, // 1: memo.MemoService.GetMemoById:input_type -> memo.GetMemoRequest
	0, // 2: memo.MemoService.CreateMemo:output_type -> memo.Memo
	0, // 3: memo.MemoService.GetMemoById:output_type -> memo.Memo
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ui_proto_memo_proto_init() }
func file_ui_proto_memo_proto_init() {
	if File_ui_proto_memo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ui_proto_memo_proto_rawDesc), len(file_ui_proto_memo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ui_proto_memo_proto_goTypes,
		DependencyIndexes: file_ui_proto_memo_proto_depIdxs,
		MessageInfos:      file_ui_proto_memo_proto_msgTypes,
	}.Build()
	File_ui_proto_memo_proto = out.File
	file_ui_proto_memo_proto_goTypes = nil
	file_ui_proto_memo_proto_depIdxs = nil
}
